services:
  dokuwiki:
    image: lscr.io/linuxserver/dokuwiki:latest
    container_name: dokuwiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/bsa/dokuwiki/data/:/config/
      - /home/bsa/dokuwiki/pages/:/config/dokuwiki/data/pages/
    ports:
      - 80:80
      - 443:443 #optional
    restart: unless-stopped
