# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 14 May 2024 09:44:03 +0000
*               @ALL          1
*               @user         8
