<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Tue, 14 May 2024 09:44:03 +0000
 */
$conf['title'] = 'Vikis wiki';
$conf['lang'] = 'de-informal';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
