# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Tue, 14 May 2024 09:44:03 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$2y$10$2NqlS6vQQ2CyGgzRyspcLeAXb4P9PCHxYHrg7S5Z6Q98tVru7w0T6:admin:admin@admin.admin:admin,user
